#! /bin/sh

sxhkd &


#########polybar######################
$HOME/.config/polybar/launch.sh
$HOME/.config/picom/launch.sh


bspc monitor -d 1 2 3 4 5 

bspc config border_width        4
bspc config window_gap          10
bspc config top_padding         35
bspc config bottom_padding      15
bspc config left_padding        15
bspc config right_padding       15
bspc config split_ratio         0.52

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color5"
bspc config presel_feedback_color "$color1"